In [62]:
import numpy as np
import pandas as pd 
#from IPython.display import Image

In [63]:
#Input array
X=np.array([[0,0],[0,1],[1,0]])

#Output
y=np.array([[0],[1],[1]])

In [64]:
np.hstack([X, y])


array([[0, 0, 0],
       [0, 1, 1],
       [1, 0, 1]])

In [65]:
#Image('./nnets-example_sketch1-2.png')

In [72]:

# Parameters of the NN
n_iter = 20
learning_rate = 0.1
input_layer_nodes = X.shape[1]
print(input_layer_nodes)
hidden_layer_nodes = 2
output_layer_nodes = y.shape[1]
print(output_layer_nodes)

2
1


In [73]:
def sigmoid(x) : 
    return(1.0 / (1.0 + np.exp(-x)))

def derivative_sigmoid(x) : 
    return(x * (1 - x))


weights_i_h = np.random.uniform(size=(input_layer_nodes, hidden_layer_nodes))
print(weights_i_h)
print("*" *100)
bias_i_h = np.random.uniform(size=(1, hidden_layer_nodes))

weights_h_o = np.random.uniform(size = (hidden_layer_nodes, output_layer_nodes))
bias_h_o = np.random.uniform(size=(1, output_layer_nodes))


# Feed Forward
for i in range(n_iter) : 
    hidden_layer_association = np.dot(X, weights_i_h) + bias_i_h
    hidden_layer_activation = sigmoid (hidden_layer_association)
 
    output_layer_association = np.dot(hidden_layer_activation, weights_h_o) + bias_h_o
    output_layer_activation = sigmoid(output_layer_association)
    prediction = output_layer_activation
    
    # Back Propagation 
    
    error = y - prediction
    #print("Error is:",error)
    slope_output_layer = derivative_sigmoid(prediction)
    slope_hidden_layer = derivative_sigmoid(hidden_layer_activation)
    
    d_output_layer = error * slope_output_layer
    
    error_hidden_layer = d_output_layer.dot (weights_h_o.T)
    d_hidden_layer = error_hidden_layer * slope_hidden_layer
    
    weights_h_o += hidden_layer_activation.T.dot(d_output_layer) * learning_rate
    bias_h_o += np.sum(d_output_layer) * learning_rate
    
    weights_i_h += X.T.dot(d_hidden_layer) * learning_rate
    bias_i_h += np.sum(d_hidden_layer) * learning_rate
    
    print(prediction.T)

[[0.87989752 0.43004583]
 [0.73869908 0.31832002]]
****************************************************************************************************
[[0.81744794 0.8325138  0.83554343]]
[[0.8152219  0.83032456 0.83336272]]
[[0.81298841 0.82812585 0.83117209]]
[[0.81074861 0.82591883 0.82897269]]
[[0.80850365 0.82370464 0.82676566]]
[[0.80625473 0.8214845  0.82455223]]
[[0.80400304 0.81925962 0.82233359]]
[[0.80174981 0.81703124 0.82011101]]
[[0.79949626 0.81480062 0.81788573]]
[[0.79724364 0.81256904 0.81565903]]
[[0.79499319 0.81033777 0.81343221]]
[[0.79274617 0.80810811 0.81120657]]
[[0.79050383 0.80588137 0.80898341]]
[[0.78826742 0.80365882 0.80676402]]
[[0.78603818 0.80144178 0.80454973]]
[[0.78381733 0.79923152 0.80234182]]
[[0.7816061  0.79702933 0.80014158]]
[[0.77940569 0.79483647 0.7979503 ]]
[[0.77721726 0.79265418 0.79576922]]
[[0.77504199 0.79048369 0.79359959]]


### Predicting from the Neural Network

In [74]:
test_data = np.array([[1,1]])

hidden_layer_association = np.dot(test_data, weights_i_h) + bias_i_h
hidden_layer_activation = sigmoid (hidden_layer_association)

output_layer_association = np.dot(hidden_layer_activation, weights_h_o) + bias_h_o
output_layer_activation = sigmoid(output_layer_association)
prediction = output_layer_activation
print(prediction)

[[0.80100307]]
