### Write a program to implement k-Nearest Neighbour algorithm to classify the iris data set. Print both correct and wrong predictions. Java/Python ML library classes can be used for this problem.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split 

from sklearn.metrics import accuracy_score, confusion_matrix

In [7]:
iris = load_iris()

x = iris.data
y = iris.target
print(y)
print('Size of Iris dataset : ', x.shape)
print('Size of Iris dataset : ', y.shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Size of Iris dataset :  (150, 4)
Size of Iris dataset :  (150,)


In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [21]:
print('Size of Train dataset : ', x_train.shape)
print('Size of Train targets : ', y_train.shape)

print('Size of Test dataset : ', x_test.shape)
print('Size of Test targets : ', y_test.shape)

Size of Train dataset :  (105, 4)
Size of Train targets :  (105,)
Size of Test dataset :  (45, 4)
Size of Test targets :  (45,)


In [22]:
knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [23]:
predictions = knn_model.predict(x_test)
print(predictions)

[2 2 2 1 2 0 1 1 1 0 2 1 2 0 0 2 1 0 1 1 1 0 0 0 1 1 0 0 1 1 1 2 0 2 0 0 1
 0 1 0 2 1 2 2 0]


In [25]:
print("Training accuracy Score is : ", accuracy_score(y_train, knn_model.predict(x_train)))
print("Testing accuracy Score is : ", accuracy_score(y_test, knn_model.predict(x_test)))


print("Training Confusion Matrix is : \n", confusion_matrix(y_train, knn_model.predict(x_train)))
print("Testing Confusion Matrix is : \n", confusion_matrix(y_test, knn_model.predict(x_test)))


Training accuracy Score is :  0.9619047619047619
Testing accuracy Score is :  0.9777777777777777
Training Confusion Matrix is : 
 [[34  0  0]
 [ 0 31  3]
 [ 0  1 36]]
Testing Confusion Matrix is : 
 [[16  0  0]
 [ 0 16  0]
 [ 0  1 12]]
